### ISSUE TITLE
Problem after installation

### ISSUE THREAD

**Issue by yanliom** [opensalt/opensalt#264]
Hello,

I installed Open Salt on a new CentOS 7 server with SELinux set to permissive.
When I visit the url I get the following error (http://83.212.238.173:3000/):

`Fatal error: Uncaught RuntimeException: Unable to create the cache directory (/var/www/html/var/cache/prod) in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:672 Stack trace: #0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(572): Symfony\Component\HttpKernel\Kernel->buildContainer() #1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(117): Symfony\Component\HttpKernel\Kernel->initializeContainer() #2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(166): Symfony\Component\HttpKernel\Kernel->boot() #3 /var/www/html/web/app.php(26): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 672`

Can you please give me some insight?

Thank you

**Comment by roverwolf** [comment]
This indicates a permission issue, running `sudo chmod -R 777 var/cache var/logs` from the top level of the repository will fix the problem.

https://github.com/opensalt/opensalt/wiki/Troubleshooting

**Comment by yanliom** [comment]
Thank you for the quick reply!
Is that a permissions problem with docker container or with host?

**Comment by roverwolf** [comment]
It is due to a mis-match between the host user and the user running the code within the docker container.

The container currently runs the code as the `www-data` user (uid and gid 33) which probably does not match the uid of the host user that has checked out the repository.  This means that if the cache directory is only read/write to the host user then the container user cannot create the cache files.

We are planning on making some larger changes to how the containers are set up in OpenSALT v2 (such as merging the nginx and phpfpm containers and running some scripts on container start-up) that should remedy this issue.

**Comment by yanliom** [comment]
Thank you for your prompt replies and the comprehensive help!
The problem was resolved.
