### ISSUE TITLE
Allow underline in markdown

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#273]

**Comment by roverwolf** [comment]
Related to #229 which [asked the question](https://github.com/opensalt/opensalt/issues/229#issuecomment-341160279) of what syntax we want to use to add underlining.

#253 added some HTML tags which allows using `<u>...</u>` to add underlining.

With this issue, did we want to extend the markdown syntax to add a way to do underlining?  If so, we need to determine what syntax we want to use.

**Comment by BarbAllen** [comment]
Jira #2818

**Comment by roverwolf** [comment]
PR #305 now parses \_abc_ to be dispalyed with \<u> instead of \<em>

**Comment by jmarks** [comment]
I want to make sure we are not breaking starndard markdown as defined here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

> _test_

 is strong emphasis. We should use HTML only for underline OR provide a new Markdown for underline. However, neither is a great solution.

**Comment by roverwolf** [comment]
I think *standard* markdown would be considered the [CommonMark](http://spec.commonmark.org) spec.

Underscores before and after normally indicate emphasis (not *strong* emphasis), which this **does break**.

What new *markdown* syntax would you suggest?

One could possibly argue that underlining is a form of emphasis, but the CommonMark spec does specify \<em> as the HTML that would be generated (Also note that \<u> was deprecated and is technically not "underline" in HTML5).

Please re-open this issue or create a new one if this is a problem as commenting on closed issues is not easily findable and makes it look like the issue is still resolved.
