### ISSUE TITLE
Duplicate cfitems are imported if user import a spreadsheet without adding association types 

### ISSUE THREAD

**Issue by sajeed42** [opensalt/opensalt#470]
Steps:

    login as superuser
    Click on framework to open
    add association of framework with types other than 'ischildof'
    click on export button
    delete that framework by click on delete button
    again try and import same delete framework
    verify its showing duplicate framework on the framework detail page

Actual:

Duplicate cfitems are imported if user import a spreadsheet without adding association types 

Expected:

It should show only single framework and its statement without showing duplicates.

For more clarification please refer attached spreadsheet
[Testing_demo.xlsx](https://github.com/opensalt/opensalt/files/1906855/Testing_demo.xlsx)

http://frameworks-staging.act.org/cftree/doc/643

**Comment by roverwolf** [comment]
(noting that this was found in 2.1-dev)

Additional observations:
It appears that there is only one copy of each CFItem, but they are all being displayed twice.  Makes me suspect that the isChildOf is being created once due to the hierarchy from the CF Item tab in the spreadsheet and then again from the isChildOf association in the CF Association tab.

**Comment by brandonopened** [comment]
closed with #496
