### ISSUE TITLE
Add RelatedFrom as possibility to CSV importer or find another way to do this?

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#500]
As a user uploading a CSV file, I want to enable associations "IsRelatedFrom" so that they appear "IsRelatedTo" from source frameworks.

Context: 
http://youtu.be/aXAypsrpaT8?hd=1

I THINK the best thing would be to let the CSV file allow for IsrelatedFrom but not sure if there is something about framework ownership/security that would prevent that from happening regardless.

**Comment by roverwolf** [comment]
From the video, it looks like the issue is in displaying the association as we can see that the association does get created.

* There is a known issue (#254) where associations pulled from other frameworks do not show up when the page is loaded directly to the CFItems, but clicking another item and clicking back will show it.
* After a quick look, it looks like the association view only displays associations that belong to the framework being viewed, not all associations that satisfy either a) belong to the framework or b) reference a CFItem in the framework (either origin or destination).

**Comment by brandonopened** [comment]
Ah, will close this in favor of eventually working on fixing #254
