### ISSUE TITLE
Copy Framework works but cache needs to be cleared everytime

### ISSUE THREAD

**Issue by sarellat** [opensalt/opensalt#646]
As an opensalt editor, when I try to copy a framework with exact match identifiers TO another framework  it's doesn't reflect right away but it needs you to clear the cache

 
Expected Behavior:

I can copy a framework with exact match associations to or from another framework with data and application integrity. 

Steps: 

*Create a new blank framework
*Navigate to another framework (draft or below) on the same server
*Select Copy Framework from the Cf Doc Page
*Select the second option., "copy with exact match identifiers"
*It SHOULD copy the framework and ExactMatch associations for each item from the origin framework 
 to the destination.

**Comment by jmarks** [comment]
Thank you sarellat. Are you using the Dev branch? By doesn't get reflected, what exactly do you mean?

**Comment by sarellat** [comment]
@jmarks It was on staging http://frameworks-staging.act.org/cfdoc/ , where you need to clear the cache everytime when you copy one framework to/from another. You can't see the copied frameworks right away.

**Comment by brandonopened** [comment]
Agreed, needs a “refresh UI” command at The end of the operation

Open Standards, Open possibilities

________________________________

**Comment by JorgeLu1s** [comment]
Steps to reproduce this bug:

**Comment by JorgeLu1s** [comment]
Steps to reproduce this bug:

Since you have two frameworks, `Framework A` and `Framework B` and you want to copy `Framework A` to `Framework B` you have to:

1. Go to `Framework A` and click on `Copy Framework ` button.
2. Select the `Framework B` in the dropdown
3. Select the second option _copy with exact match identifiers_ and click on `Copy`
4. You go to `Framework B` and you should see all the items and associations of `Framework A`
